[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
description = "Fast GPIO interfaces for Linux"
documentation = "https://docs.rs/gpio"
license = "MIT"
name = "gpio"
repository = "https://github.com/mbr/gpio-rs"
version = "0.4.1"

[dependencies]
nix = "0.10.0"
