[package]
name = "gpio"
version = "0.2.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
repository = "https://github.com/mbr/gpio-rs"
docs = "https://docs.rs/gpio"
license = "MIT"
description = "Fast GPIO interfaces for Linux"

[dependencies]

